In [2]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import plotly.graph_objects as go
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,roc_curve,auc
#from pyod.models.mad import MAD

In [210]:
#df=pd.read_csv('pageblocks.csv')
#df=pd.read_csv('satellite-unsupervised-ad.csv')
#df=pd.read_csv('PenDigits.csv')
#df=pd.read_csv('OpticalDigits.csv')
#df=pd.read_csv('SatImage.csv')
#df=pd.read_csv('Waveform.csv')
df=pd.read_csv('ANN-Thyroid.csv')
#df=pd.read_csv('letter-unsupervised-ad.csv')
#df=pd.read_csv('ALOI.csv')
df.shape

(7199, 22)

In [211]:
y=df.iloc[:,-1]
unique, counts = np.unique(y, return_counts=True)
dict_X = dict(zip(unique, counts))
dict_X

{'inlier': 6666, 'outlier': 533}

In [212]:
from sklearn import preprocessing
for x in df.columns:
    while df[x].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(df[x].values))
        df[x] = lbl.transform(list(df[x].values))

In [213]:
df.columns

Index(['0.29', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       '0.9', '0.10', '0.11', '0.12', '0.13', '0.14', '0.0061', '0.028',
       '0.111', '0.131', '0.085', 'outlier'],
      dtype='object')

In [214]:
result=df.iloc[:,:-1]
data=result.copy()
y_true=df[['outlier']]

In [164]:
# analysis of knn
from pyod.models.knn import KNN
knn = KNN()
knn.fit(data)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [165]:
result['Outlier_knn']=knn.predict(data)
y_pred_knn=result[['Outlier_knn']]
y_score_knn=knn.predict_proba(data)[:,1]
confusion_matrix(y_true,y_pred_knn)

array([[6108,  558],
       [ 448,   85]], dtype=int64)

In [166]:
#KNN results without decomposition
fpr_knn, tpr_knn, thresholds_knn = roc_curve(y_true, y_score_knn,pos_label=1)
print('Precision: %.3f' % precision_score(y_true, y_pred_knn))
print('Recall: %.3f' % recall_score(y_true, y_pred_knn))
print('f1_score: %.3f' % f1_score(y_true, y_pred_knn))
print('AUC: %.3f' % auc(fpr_knn, tpr_knn))

Precision: 0.132
Recall: 0.159
f1_score: 0.145
AUC: 0.638


In [215]:
cluster = KMeans(n_clusters=5)
cluster.fit_predict(data)

array([4, 4, 4, ..., 4, 1, 4])

In [216]:
df['cluster']=pd.Categorical(cluster.labels_)

cluster_1=df.query('cluster==0')
cluster_2=df.query('cluster==1')
cluster_3=df.query('cluster==2')
cluster_4=df.query('cluster==3')
cluster_5=df.query('cluster==4')

In [217]:
dt_1=cluster_1.iloc[:,:-1]
dt_2=cluster_2.iloc[:,:-1]
dt_3=cluster_3.iloc[:,:-1]
dt_4=cluster_4.iloc[:,:-1]
dt_5=cluster_5.iloc[:,:-1]

In [218]:
#iteration_1
data_1=cluster_1.iloc[:,:-2]
data_2=cluster_2.iloc[:,:-2]
data_3=cluster_3.iloc[:,:-2]
data_4=cluster_4.iloc[:,:-2]
data_5=cluster_5.iloc[:,:-2]

data_1.reset_index(drop=True, inplace=True)
data_2.reset_index(drop=True, inplace=True)
data_3.reset_index(drop=True, inplace=True)
data_4.reset_index(drop=True, inplace=True)
data_5.reset_index(drop=True, inplace=True)

print('data points in cluster_1 initeration_1::', data_1.shape[0])
print('data points in cluster_2 initeration_1::', data_2.shape[0])
print('data points in cluster_3 initeration_1::', data_3.shape[0])
print('data points in cluster_4 initeration_1::', data_4.shape[0])
print('data points in cluster_5 initeration_1::', data_5.shape[0])


data points in cluster_1 initeration_1:: 881
data points in cluster_2 initeration_1:: 1763
data points in cluster_3 initeration_1:: 495
data points in cluster_4 initeration_1:: 344
data points in cluster_5 initeration_1:: 3716


In [219]:
#cluster_1 outlier detection
knn1 = KNN()
knn1.fit(data_1)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [220]:
#cluster_2 outlier detection
knn2 = KNN()
knn2.fit(data_2)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [221]:
#cluster_3 outlier detection
knn3 = KNN()
knn3.fit(data_3)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [222]:
#cluster_4 outlier detection
knn4 = KNN()
knn4.fit(data_4)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [223]:
#cluster_4 outlier detection
knn5 = KNN()
knn5.fit(data_5)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [224]:
#od results
dt_1['od']=knn1.predict(data_1)
dt_2['od']=knn2.predict(data_2)
dt_3['od']=knn3.predict(data_3)
dt_4['od']=knn4.predict(data_4)
dt_5['od']=knn5.predict(data_5)

dt_1['prob']=knn1.predict_proba(data_1)[:,1]
dt_2['prob']=knn2.predict_proba(data_2)[:,1]
dt_3['prob']=knn3.predict_proba(data_3)[:,1]
dt_4['prob']=knn4.predict_proba(data_4)[:,1]
dt_5['prob']=knn5.predict_proba(data_5)[:,1]

In [225]:
#combine the cluster
com=pd.concat([dt_1,dt_2,dt_3,dt_4,dt_5],axis=0)
com.reset_index(drop=True, inplace=True)
com.shape

(7199, 24)

In [226]:
y_tr=com[['outlier']]
y_pr=com[['od']]
y_sc=com[['prob']]
confusion_matrix(y_tr,y_pr)

array([[6160,  506],
       [ 433,  100]], dtype=int64)

In [176]:
#KNN results with decomposition(k=2)
fpr_com1, tpr_com1, thresholds_com1 = roc_curve(y_tr, y_sc,pos_label=1)
print('Precision: %.3f' % precision_score(y_tr, y_pr))
print('Recall: %.3f' % recall_score(y_tr, y_pr))
print('f1_score: %.3f' % f1_score(y_tr, y_pr))
print('AUC: %.3f' % auc(fpr_com1, tpr_com1))

Precision: 0.134
Recall: 0.161
f1_score: 0.146
AUC: 0.648


In [192]:
#KNN results with decomposition(k=3)
fpr_com2, tpr_com2, thresholds_com2 = roc_curve(y_tr, y_sc,pos_label=1)
print('Precision: %.3f' % precision_score(y_tr, y_pr))
print('Recall: %.3f' % recall_score(y_tr, y_pr))
print('f1_score: %.3f' % f1_score(y_tr, y_pr))
print('AUC: %.3f' % auc(fpr_com2, tpr_com2))

Precision: 0.146
Recall: 0.171
f1_score: 0.157
AUC: 0.678


In [209]:
#KNN results with decomposition(k=4)
fpr_com3, tpr_com3, thresholds_com3 = roc_curve(y_tr, y_sc,pos_label=1)
print('Precision: %.3f' % precision_score(y_tr, y_pr))
print('Recall: %.3f' % recall_score(y_tr, y_pr))
print('f1_score: %.3f' % f1_score(y_tr, y_pr))
print('AUC: %.3f' % auc(fpr_com3, tpr_com3))

Precision: 0.120
Recall: 0.139
f1_score: 0.129
AUC: 0.654


In [227]:
#KNN results with decomposition(k=5)
fpr_com4, tpr_com4, thresholds_com4 = roc_curve(y_tr, y_sc,pos_label=1)
print('Precision: %.3f' % precision_score(y_tr, y_pr))
print('Recall: %.3f' % recall_score(y_tr, y_pr))
print('f1_score: %.3f' % f1_score(y_tr, y_pr))
print('AUC: %.3f' % auc(fpr_com4, tpr_com4))

Precision: 0.165
Recall: 0.188
f1_score: 0.176
AUC: 0.681


In [229]:
#ROC analysis
import plotly.graph_objects as go

fig = go.Figure()
fig.add_shape(
    type='line', line=dict(dash='dash'),
    x0=0, x1=1, y0=0, y1=1)

fig.add_trace(go.Scatter(x=fpr_knn, y=tpr_knn, name=f'kNN(AUC={auc(fpr_knn, tpr_knn):.4f})', mode='lines',marker_color='crimson'))
fig.add_trace(go.Scatter(x=fpr_com1, y=tpr_com1, name=f'AD(k=2)(AUC={auc(fpr_com1, tpr_com1):.4f})', mode='lines',marker_color='hotpink'))
fig.add_trace(go.Scatter(x=fpr_com2, y=tpr_com2, name=f'AD(k=3)(AUC={auc(fpr_com2, tpr_com2):.4f})', mode='lines'))
fig.add_trace(go.Scatter(x=fpr_com3, y=tpr_com3, name=f'AD(k=4)(AUC={auc(fpr_com3, tpr_com3):.4f})', mode='lines'))
fig.add_trace(go.Scatter(x=fpr_com4, y=tpr_com4, name=f'AD(k=5)(AUC={auc(fpr_com4, tpr_com4):.4f})', mode='lines'))

fig.update_layout(
    xaxis_title='False Positive Rate',
    yaxis_title='True Positive Rate',
    yaxis=dict(scaleanchor="x", scaleratio=1),
    xaxis=dict(constrain='domain'),
    width=700, height=600)
fig.show()
